# @no-cookie-jar
### GET request to example server
POST {{TURING_API_URL}}/users/login
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "password": "123456"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("refresh_token", response.body.refreshToken);
    client.global.set("email", response.body.email);
%}
###

# @no-cookie-jar
POST {{TURING_API_URL}}/users/logout
Content-Type: application/json
Authorization: Bearer {{refresh_token}}


###
GET {{TURING_API_URL}}/auths/admin/details

# @no-cookie-jar
###
GET {{TURING_API_URL}}/auths/
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{TURING_API_URL}}/company/users?fullname=Ali&page=0&size=5
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{TURING_API_URL}}/company/users?page=0&size=14&groups=vendedores%2ccontadores
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{TURING_API_URL}}/company/groups
Accept: application/json
Authorization: Bearer {{auth_token}}

###
DELETE {{TURING_API_URL}}/company/users/Robert@gmail.com
Accept: application/json
Authorization: Bearer {{auth_token}}

###
POST {{TURING_API_URL}}/company/users/gonza@gmail.com
Accept: application/json
Authorization: Bearer {{auth_token}}

